package ca.mcgill.ecse321.boardgamehub.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.ResponseStatus;
import org.springframework.web.bind.annotation.RestController;

import ca.mcgill.ecse321.boardgamehub.model.Review;
import ca.mcgill.ecse321.boardgamehub.service.ReviewService;
import ca.mcgill.ecse321.boardgamehub.dto.ReviewResponseDto;
import ca.mcgill.ecse321.boardgamehub.dto.ReviewCreationDto;

@RestController
public class ReviewController {
    @Autowired
    private ReviewService reviewService;

    /**
     * Create a review for a particular game
     * 
     * @param reviewToCreate the review to be created
     * @return The created review, including their autogenerated Id
     */
    @PostMapping("reviews")
    @ResponseStatus(HttpStatus.CREATED)
    public ReviewResponseDto createReview(@RequestBody ReviewCreationDto reviewToCreate) {
        Review createdReview = reviewService.createReview(reviewToCreate);
        return new ReviewResponseDto(createdReview);
    }

    /**
     * Find a specific review by Id
     * 
     * @param id The primary key of the review to find
     * @return The review with that id
     */
    @GetMapping("reviews/{id}")
    public ReviewResponseDto findReviewById(@PathVariable int id) {
        Review review = reviewService.findReviewById(id);
        return new ReviewResponseDto(review);
    }
}
